EnvironmentManager.flightRecordingEnabled=false
EnvironmentManager.decoratorEventRecordingEnabled=false
EnvironmentManager.debugRomcomMetrics=false
# delay for simulating slow requests
MessageTransportLayerServer.ReceiveChannelImpl.receiveDelay=0
Environment.invokeSyncTimeoutSecs=30
Environment.invokeSyncPermitted=true