
/* from BrowserChannel.BROWSERCHANNEL_PROTOCOL_VERSION */
class gwt_hm_BrowserChannel{
  
}
gwt_hm_BrowserChannel.BROWSERCHANNEL_PROTOCOL_VERSION=2

/* from com.google.gwt.dev.shell.BrowserChannel.SpecialDispatchId */
gwt_hm_BrowserChannel.SPECIAL_HAS_METHOD=0
gwt_hm_BrowserChannel.SPECIAL_HAS_PROPERTY=1
gwt_hm_BrowserChannel.SPECIAL_GET_PROPERTY=2
gwt_hm_BrowserChannel.SPECIAL_SET_PROPERTY=3

/* from com.google.gwt.dev.shell.BrowserChannel.MessageType */
gwt_hm_BrowserChannel.MESSAGE_TYPE_INVOKE=0
gwt_hm_BrowserChannel.MESSAGE_TYPE_RETURN=1
gwt_hm_BrowserChannel.MESSAGE_TYPE_OLD_LOAD_MODULE=2
gwt_hm_BrowserChannel.MESSAGE_TYPE_QUIT=3
gwt_hm_BrowserChannel.MESSAGE_TYPE_LOADJSNI=4
gwt_hm_BrowserChannel.MESSAGE_TYPE_INVOKESPECIAL=5
gwt_hm_BrowserChannel.MESSAGE_TYPE_FREEVALUE=6
gwt_hm_BrowserChannel.MESSAGE_TYPE_FATAL_ERROR=7
gwt_hm_BrowserChannel.MESSAGE_TYPE_CHECK_VERSIONS=8
gwt_hm_BrowserChannel.MESSAGE_TYPE_PROTOCOL_VERSION=9
gwt_hm_BrowserChannel.MESSAGE_TYPE_CHOOSE_TRANSPORT=10
gwt_hm_BrowserChannel.MESSAGE_TYPE_SWITCH_TRANSPORT=11
gwt_hm_BrowserChannel.MESSAGE_TYPE_LOAD_MODULE=12

/* from com.google.gwt.dev.shell.BrowserChannel.Value.ValueType */
gwt_hm_BrowserChannel.VALUE_TYPE_NULL=0
gwt_hm_BrowserChannel.VALUE_TYPE_BOOLEAN=1
gwt_hm_BrowserChannel.VALUE_TYPE_BYTE=2
gwt_hm_BrowserChannel.VALUE_TYPE_CHAR=3
gwt_hm_BrowserChannel.VALUE_TYPE_SHORT=4
gwt_hm_BrowserChannel.VALUE_TYPE_INT=5
gwt_hm_BrowserChannel.VALUE_TYPE_LONG=6
gwt_hm_BrowserChannel.VALUE_TYPE_FLOAT=7
gwt_hm_BrowserChannel.VALUE_TYPE_DOUBLE=8
gwt_hm_BrowserChannel.VALUE_TYPE_STRING=9
gwt_hm_BrowserChannel.VALUE_TYPE_JAVA_OBJECT=10
gwt_hm_BrowserChannel.VALUE_TYPE_JS_OBJECT=11
gwt_hm_BrowserChannel.VALUE_TYPE_UNDEFINED=12
