function cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient(){var N='bootstrap',O='begin',P='gwt.codesvr.cc.alcina.framework.servlet.component.romcom.RemoteObjectModelComponentClient=',Q='gwt.codesvr=',R='gwt.l',S='cc.alcina.framework.servlet.component.romcom.RemoteObjectModelComponentClient',T='startup',U='DUMMY',V=0,W=1,X='iframe',Y='position:absolute; width:0; height:0; border:none; left: -1000px;',Z=' top: -1000px;',$='CSS1Compat',_='<!doctype html>',ab='',bb='<html><head><\/head><body><\/body><\/html>',cb='undefined',db='readystatechange',eb=10,fb='script',gb='javascript',hb='cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient',ib='Failed to load ',jb='moduleStartup',kb='scriptTagAdded',lb='moduleRequested',mb='meta',nb='name',ob='cc.alcina.framework.servlet.component.romcom.RemoteObjectModelComponentClient::',pb='::',qb='gwt:property',rb='content',sb='=',tb='gwt:onPropertyErrorFn',ub='Bad handler "',vb='" for "gwt:onPropertyErrorFn"',wb='gwt:onLoadErrorFn',xb='" for "gwt:onLoadErrorFn"',yb='#',zb='?',Ab='/',Bb='img',Cb='clear.cache.gif',Db='baseUrl',Eb='cc.alcina.framework.servlet.component.romcom.RemoteObjectModelComponentClient.nocache.js',Fb='base',Gb='//',Hb='selectingPermutation',Ib='cc.alcina.framework.servlet.component.romcom.RemoteObjectModelComponentClient.devmode.js',Jb='FC64E466C173E46C29A6F51F7C84E793',Kb=':',Lb='.cache.js',Mb='loadExternalRefs',Nb='end',Ob='http:',Pb='file:',Qb='_gwt_dummy_',Rb='__gwtDevModeHook:cc.alcina.framework.servlet.component.romcom.RemoteObjectModelComponentClient',Sb='Ignoring non-whitelisted Dev Mode URL: ',Tb=':moduleBase',Ub='head';var n=window;var o=document;q(N,O);function p(){var a=n.location.search;return a.indexOf(P)!=-1||(a.indexOf(Q)!=-1||a.indexOf(R)!=-1)}
function q(a,b){if(n.__gwtStatsEvent){n.__gwtStatsEvent({'moduleName':S,'sessionId':n.__gwtStatsSessionId,'subSystem':T,'evtGroup':a,'millis':(new Date).getTime(),'type':b})}}
cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__sendStats=q;cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__moduleName=S;cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__errFn=null;cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__moduleBase=U;cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__softPermutationId=V;cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__computePropValue=null;cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__getPropMap=null;cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__installRunAsyncCode=function(){};cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__gwtStartLoadingFragment=function(){return null};cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__gwt_isKnownPropertyValue=function(){return false};cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__gwt_getMetaProperty=function(){return null};var r=null;var s=n.__gwt_activeModules=n.__gwt_activeModules||{};s[S]={'moduleName':S};cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__moduleStartupDone=function(e){var f=s[S].bindings;s[S].bindings=function(){var a=f?f():{};var b=e[cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__softPermutationId];for(var c=V;c<b.length;c++){var d=b[c];a[d[V]]=d[W]}return a}};var t;function u(){v();return t}
function v(){if(t){return}var a=o.createElement(X);a.id=S;a.style.cssText=Y+Z;a.tabIndex=-1;o.body.appendChild(a);t=a.contentDocument;if(!t){t=a.contentWindow.document}t.open();var b=document.compatMode==$?_:ab;t.write(b+bb);t.close()}
function w(f){function g(a){function b(){if(typeof o.readyState==cb){return typeof o.body!=cb&&o.body!=null}return /loaded|complete/.test(o.readyState)}
var c=b();if(c){a();return}function d(){if(!c){if(!b()){return}c=true;a();if(o.removeEventListener){o.removeEventListener(db,d,false)}if(e){clearInterval(e)}}}
if(o.addEventListener){o.addEventListener(db,d,false)}var e=setInterval(function(){d()},eb)}
function h(a){var b=u();var c=b.body;var d=b.createElement(fb);d.language=gb;d.src=a;if(cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__errFn){d.onerror=function(){cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__errFn(hb,new Error(ib+a))}}c.appendChild(d);q(jb,kb)}
q(jb,lb);g(function(){h(f)})}
cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__startLoadingFragment=function(a){return C(a)};cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__installRunAsyncCode=function(a){var b=u();var c=b.body;var d=b.createElement(fb);d.language=gb;d.text=a;c.appendChild(d);c.removeChild(d)};function A(){var c={};var d;var e;var f=o.getElementsByTagName(mb);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(nb),k;if(j){j=j.replace(ob,ab);if(j.indexOf(pb)>=V){continue}if(j==qb){k=i.getAttribute(rb);if(k){var l,m=k.indexOf(sb);if(m>=V){j=k.substring(V,m);l=k.substring(m+W)}else{j=k;l=ab}c[j]=l}}else if(j==tb){k=i.getAttribute(rb);if(k){try{d=eval(k)}catch(a){alert(ub+k+vb)}}}else if(j==wb){k=i.getAttribute(rb);if(k){try{e=eval(k)}catch(a){alert(ub+k+xb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};r=d;cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(yb);if(b==-1){b=a.length}var c=a.indexOf(zb);if(c==-1){c=a.length}var d=a.lastIndexOf(Ab,Math.min(c,b));return d>=V?a.substring(V,d+W):ab}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=o.createElement(Bb);b.src=a+Cb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Db);if(a!=null){return a}return ab}
function h(){var a=o.getElementsByTagName(fb);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Eb)!=-1){return e(a[b].src)}}return ab}
function i(){var a=o.getElementsByTagName(Fb);if(a.length>V){return a[a.length-W].href}return ab}
function j(){var a=o.location;return a.href==a.protocol+Gb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==ab){k=h()}if(k==ab){k=i()}if(k==ab&&j()){k=e(o.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__moduleBase+a}
function D(){var f=[];var g=V;var h=[];var i=[];function j(a){var b=i[a](),c=h[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(r){r(a,d,b)}throw null}
__gwt_isKnownPropertyValue=function(a,b){return b in h[a]};cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__getPropMap=function(){var a={};for(var b in h){if(h.hasOwnProperty(b)){a[b]=j(b)}}return a};cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__computePropValue=j;n.__gwt_activeModules[S].bindings=cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__getPropMap;q(N,Hb);if(p()){return C(Ib)}var k;try{k=Jb;var l=k.indexOf(Kb);if(l!=-1){g=parseInt(k.substring(l+W),eb);k=k.substring(V,l)}}catch(a){}cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__softPermutationId=g;return C(k+Lb)}
function F(){if(!n.__gwt_stylesLoaded){n.__gwt_stylesLoaded={}}q(Mb,O);q(Mb,Nb)}
A();cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__moduleBase=B();s[S].moduleBase=cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__moduleBase;var G=D();if(n){var H=!!(n.location.protocol==Ob||n.location.protocol==Pb);n.__gwt_activeModules[S].canRedirect=H;function I(){var b=Qb;try{n.sessionStorage.setItem(b,b);n.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(H&&I()){var J=Rb;var K=n.sessionStorage[J];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(K)){if(K&&(window.console&&console.log)){console.log(Sb+K)}K=ab}if(K&&!n[J]){n[J]=true;n[J+Tb]=B();var L=o.createElement(fb);L.src=K;var M=o.getElementsByTagName(Ub)[V];M.insertBefore(L,M.firstElementChild||M.children[V]);return false}}}F();q(N,Nb);w(G);return true}
cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.succeeded=cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient();