function cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient(){var N='bootstrap',O='begin',P='gwt.codesvr.cc.alcina.framework.servlet.component.romcom.RemoteObjectModelComponentClient=',Q='gwt.codesvr=',R='gwt.l',S='cc.alcina.framework.servlet.component.romcom.RemoteObjectModelComponentClient',T='startup',U='DUMMY',V=0,W=1,X='iframe',Y='Javascript container. No human-readable content',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',$=' top: -1000px;',_='CSS1Compat',ab='<!doctype html>',bb='',cb='<html><head><\/head><body><\/body><\/html>',db='undefined',eb='readystatechange',fb=10,gb='script',hb='javascript',ib='cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient',jb='Failed to load ',kb='moduleStartup',lb='scriptTagAdded',mb='moduleRequested',nb='meta',ob='name',pb='cc.alcina.framework.servlet.component.romcom.RemoteObjectModelComponentClient::',qb='::',rb='gwt:property',sb='content',tb='=',ub='gwt:onPropertyErrorFn',vb='Bad handler "',wb='" for "gwt:onPropertyErrorFn"',xb='gwt:onLoadErrorFn',yb='" for "gwt:onLoadErrorFn"',zb='#',Ab='?',Bb='/',Cb='img',Db='clear.cache.gif',Eb='baseUrl',Fb='cc.alcina.framework.servlet.component.romcom.RemoteObjectModelComponentClient.nocache.js',Gb='base',Hb='//',Ib='selectingPermutation',Jb='cc.alcina.framework.servlet.component.romcom.RemoteObjectModelComponentClient.devmode.js',Kb='197DF5EF9B8D785BCAE95F3E49182D06',Lb=':',Mb='.cache.js',Nb='loadExternalRefs',Ob='end',Pb='http:',Qb='file:',Rb='_gwt_dummy_',Sb='__gwtDevModeHook:cc.alcina.framework.servlet.component.romcom.RemoteObjectModelComponentClient',Tb='Ignoring non-whitelisted Dev Mode URL: ',Ub=':moduleBase',Vb='head';var n=window;var o=document;q(N,O);function p(){var a=n.location.search;return a.indexOf(P)!=-1||(a.indexOf(Q)!=-1||a.indexOf(R)!=-1)}
function q(a,b){if(n.__gwtStatsEvent){n.__gwtStatsEvent({'moduleName':S,'sessionId':n.__gwtStatsSessionId,'subSystem':T,'evtGroup':a,'millis':(new Date).getTime(),'type':b})}}
cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__sendStats=q;cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__moduleName=S;cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__errFn=null;cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__moduleBase=U;cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__softPermutationId=V;cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__computePropValue=null;cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__getPropMap=null;cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__installRunAsyncCode=function(){};cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__gwtStartLoadingFragment=function(){return null};cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__gwt_isKnownPropertyValue=function(){return false};cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__gwt_getMetaProperty=function(){return null};var r=null;var s=n.__gwt_activeModules=n.__gwt_activeModules||{};s[S]={'moduleName':S};cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__moduleStartupDone=function(e){var f=s[S].bindings;s[S].bindings=function(){var a=f?f():{};var b=e[cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__softPermutationId];for(var c=V;c<b.length;c++){var d=b[c];a[d[V]]=d[W]}return a}};var t;function u(){v();return t}
function v(){if(t){return}var a=o.createElement(X);a.id=S;a.title=Y;a.style.cssText=Z+$;a.tabIndex=-1;o.body.appendChild(a);t=a.contentDocument;if(!t){t=a.contentWindow.document}t.open();var b=document.compatMode==_?ab:bb;t.write(b+cb);t.close()}
function w(f){function g(a){function b(){if(typeof o.readyState==db){return typeof o.body!=db&&o.body!=null}return /loaded|complete/.test(o.readyState)}
var c=b();if(c){a();return}function d(){if(!c){if(!b()){return}c=true;a();if(o.removeEventListener){o.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(o.addEventListener){o.addEventListener(eb,d,false)}var e=setInterval(function(){d()},fb)}
function h(a){var b=u();var c=b.body;var d=b.createElement(gb);d.language=hb;d.src=a;if(cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__errFn){d.onerror=function(){cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__errFn(ib,new Error(jb+a))}}c.appendChild(d);q(kb,lb)}
q(kb,mb);g(function(){h(f)})}
cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__startLoadingFragment=function(a){return C(a)};cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__installRunAsyncCode=function(a){var b=u();var c=b.body;var d=b.createElement(gb);d.language=hb;d.text=a;c.appendChild(d);c.removeChild(d)};function A(){var c={};var d;var e;var f=o.getElementsByTagName(nb);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(ob),k;if(j){j=j.replace(pb,bb);if(j.indexOf(qb)>=V){continue}if(j==rb){k=i.getAttribute(sb);if(k){var l,m=k.indexOf(tb);if(m>=V){j=k.substring(V,m);l=k.substring(m+W)}else{j=k;l=bb}c[j]=l}}else if(j==ub){k=i.getAttribute(sb);if(k){try{d=eval(k)}catch(a){alert(vb+k+wb)}}}else if(j==xb){k=i.getAttribute(sb);if(k){try{e=eval(k)}catch(a){alert(vb+k+yb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};r=d;cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(zb);if(b==-1){b=a.length}var c=a.indexOf(Ab);if(c==-1){c=a.length}var d=a.lastIndexOf(Bb,Math.min(c,b));return d>=V?a.substring(V,d+W):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=o.createElement(Cb);b.src=a+Db;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Eb);if(a!=null){return a}return bb}
function h(){var a=o.getElementsByTagName(gb);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Fb)!=-1){return e(a[b].src)}}return bb}
function i(){var a=o.getElementsByTagName(Gb);if(a.length>V){return a[a.length-W].href}return bb}
function j(){var a=o.location;return a.href==a.protocol+Hb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(o.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__moduleBase+a}
function D(){var f=[];var g=V;var h=[];var i=[];function j(a){var b=i[a](),c=h[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(r){r(a,d,b)}throw null}
__gwt_isKnownPropertyValue=function(a,b){return b in h[a]};cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__getPropMap=function(){var a={};for(var b in h){if(h.hasOwnProperty(b)){a[b]=j(b)}}return a};cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__computePropValue=j;n.__gwt_activeModules[S].bindings=cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__getPropMap;q(N,Ib);if(p()){return C(Jb)}var k;try{k=Kb;var l=k.indexOf(Lb);if(l!=-1){g=parseInt(k.substring(l+W),fb);k=k.substring(V,l)}}catch(a){}cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__softPermutationId=g;return C(k+Mb)}
function F(){if(!n.__gwt_stylesLoaded){n.__gwt_stylesLoaded={}}q(Nb,O);q(Nb,Ob)}
A();cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__moduleBase=B();s[S].moduleBase=cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.__moduleBase;var G=D();if(n){var H=!!(n.location.protocol==Pb||n.location.protocol==Qb);n.__gwt_activeModules[S].canRedirect=H;function I(){var b=Rb;try{n.sessionStorage.setItem(b,b);n.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(H&&I()){var J=Sb;var K=n.sessionStorage[J];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(K)){if(K&&(window.console&&console.log)){console.log(Tb+K)}K=bb}if(K&&!n[J]){n[J]=true;n[J+Ub]=B();var L=o.createElement(gb);L.src=K;var M=o.getElementsByTagName(Vb)[V];M.insertBefore(L,M.firstElementChild||M.children[V]);return false}}}F();q(N,Ob);w(G);return true}
cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient.succeeded=cc_alcina_framework_servlet_component_romcom_RemoteObjectModelComponentClient();