package cc.alcina.framework.common.client.reflection;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Inherited;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * A type annotated with this property should have a corresponding autogenerated
 * TypedProperty.Container class in its package's auto-generated
 * PackageProperties.java source file
 */
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Target(ElementType.TYPE)
@Inherited
public @interface TypedProperties {
}
